server: 
  port: 9001
eureka:
  client:
    serviceurl: 
      defaultzone: http://demo-eureka:8761/eureka/
spring:
  datasource:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      properties:
        metadata.broker.list: localhost:9092
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: localhost:2181
          brokers: localhost:9092
      bindings:
        firstOutput:
          destination: firstOutput
          content-type: application/json
feign: 
  hystrix: 
    enabled: false
logging:
  level:
    ROOT: INFO
    com.posco: TRACE
    com.poscoict: TRACE
