server: 
  port: 9002
eureka:
  client:
    serviceurl: 
      defaultzone: http://demo-eureka:8761/eureka/
feign: 
  hystrix: 
    enabled: false
logging:
  level:
    ROOT: INFO
    com.posco: TRACE
